### ISSUE TITLE
Create Arduino menu: Optimize page

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOSDocs#34]
Explain Optimize and use Crucible posts for explanation 
https://crucible.hubbe.net/t/arduino-proffieboard-plugin-v3-6-beta/436/18

**Comment by profezzorn** [comment]
We have a page:
https://pod.hubbe.net/howto/speeding-things-up.html

The "optimization" entry should probably be improved though.

**Comment by profezzorn** [comment]
This was fixed in pull #35
